[script:sutw_eligible_reports]
match = /sutw/v1/reports
script = sutw_rest_handler.py
scripttype = persist
handler = sutw_rest_handler.SutwRestHandler
python.version = python3
requireAuthentication = true
output_modes = json
passPayload = false
passSession = true

[script:sutw_start_batch_preview]
match = /sutw/v1/batches/preview
script = sutw_rest_handler.py
scripttype = persist
handler = sutw_rest_handler.SutwRestHandler
python.version = python3
requireAuthentication = true
output_modes = json
passPayload = true
passSession = true

[script:sutw_start_batch]
match = /sutw/v1/batches
script = sutw_rest_handler.py
scripttype = persist
handler = sutw_rest_handler.SutwRestHandler
python.version = python3
requireAuthentication = true
output_modes = json
passPayload = true
passSession = true

[script:sutw_recent_batches]
match = /sutw/v1/batches/recent
script = sutw_rest_handler.py
scripttype = persist
handler = sutw_rest_handler.SutwRestHandler
python.version = python3
requireAuthentication = true
output_modes = json
passPayload = false
passSession = true

[script:sutw_batch_status]
match = /sutw/v1/batches/status
script = sutw_rest_handler.py
scripttype = persist
handler = sutw_rest_handler.SutwRestHandler
python.version = python3
requireAuthentication = true
output_modes = json
passPayload = false
passSession = true
