[expose:sutw_eligible_reports]
methods = GET
pattern = sutw/v1/reports

[expose:sutw_start_batch_preview]
methods = POST
pattern = sutw/v1/batches/preview

[expose:sutw_start_batch]
methods = POST
pattern = sutw/v1/batches

[expose:sutw_recent_batches]
methods = GET
pattern = sutw/v1/batches/recent

[expose:sutw_batch_status]
methods = GET
pattern = sutw/v1/batches/status
